/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package base;
import base.dashboard1;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
/**
 *
 * @author HP
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class barang1 extends javax.swing.JFrame {

    private DefaultTableModel DftTblModel_barang;
private String SQL;
public void TampilData() {
        DftTblModel_barang = new DefaultTableModel();
        DftTblModel_barang.addColumn("ID BARANG");
        DftTblModel_barang.addColumn("NAMA BARANG");
        DftTblModel_barang.addColumn("HARGA BELI");
        DftTblModel_barang.addColumn("HARGA JUAL");
        DftTblModel_barang.addColumn("STOK");
        jTable1.setModel(DftTblModel_barang);
       Connection conn = koneksi.getConnection();
        try {
            java.sql.Statement stmt = conn.createStatement();
            SQL = "select * from barang";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()) {
                DftTblModel_barang.addRow(new Object[]{
                    res.getString("id_barang"),
                    res.getString("nama_barang"),
                    res.getString("harga_beli"),
                    res.getString("harga_jual"),
                    res.getString("stock")
                });
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
private void cariData(String key){
        DftTblModel_barang = new DefaultTableModel();
        DftTblModel_barang.addColumn("ID BARANG");
        DftTblModel_barang.addColumn("NAMA BARANG");
        DftTblModel_barang.addColumn("HARGA BELI");
        DftTblModel_barang.addColumn("HARGA JUAL");
        DftTblModel_barang.addColumn("STOK");
        jTable1.setModel(DftTblModel_barang);
       Connection conn = koneksi.getConnection();
        try {
            java.sql.Statement stmt = conn.createStatement();
            SQL = "select *  from barang WHERE id_barang LIKE '%"+key+"%' "
                    + "OR nama_barang LIKE '%"+key+"%' or harga_beli LIKE '%"+key+"%'"
                    + " or harga_jual LIKE '%"+key+"%' or stock LIKE '%"+key+"%' ";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()) {
                DftTblModel_barang.addRow(new Object[]{
                    res.getString("id_barang"),
                    res.getString("nama_barang"),
                    res.getString("harga_beli"),
                    res.getString("harga_jual"),
                    res.getString("stock")
                });
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    private void auto_kdBR() {
        try{
        String sql = "SELECT MAX(RIGHT(id_barang,3)) FROM barang";
        java.sql.Connection con = (Connection) koneksi.getConnection();
        java.sql.Statement st = con.createStatement();
        java.sql.ResultSet rst = st.executeQuery(sql);
        if(rst.next()) {
            String auto_kdPM, tambah;
            int kdb;
            auto_kdPM = Integer.toString(rst.getInt(1)+1);
            kdb = auto_kdPM.length();
            tambah = "";
            for (int i = 1; i <= 3 - kdb; i++ ){
                tambah = tambah + "0";
            }
            id_barang.setText("BR"+tambah+auto_kdPM);
            }
        }
        catch (Exception e) {
            id_barang.setText("BR001");
        }
    }
    
    private void clear(){
        nama_barang.setText("");
        hargabeli.setText("");
        hargajual.setText("");
        stock.setText("");
    }



    /**
     * Creates new form barang1
     */
    public barang1() {
        initComponents();this.setTitle("Barang");
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/tampilan/icon.png")));
        this.TampilData();
        auto_kdBR();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        id_barang = new javax.swing.JTextField();
        nama_barang = new javax.swing.JTextField();
        hargajual = new javax.swing.JTextField();
        hargabeli = new javax.swing.JTextField();
        stock = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cari = new javax.swing.JTextField();
        home = new javax.swing.JButton();
        EDIT = new javax.swing.JButton();
        SIMPAN = new javax.swing.JButton();
        Hapus = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        id_barang.setBackground(new java.awt.Color(255, 255, 255));
        id_barang.setBorder(null);
        id_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_barangActionPerformed(evt);
            }
        });
        id_barang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                id_barangKeyPressed(evt);
            }
        });
        jPanel1.add(id_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 165, 335, 19));

        nama_barang.setBackground(new java.awt.Color(255, 255, 255));
        nama_barang.setBorder(null);
        jPanel1.add(nama_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 221, 335, 19));

        hargajual.setBackground(new java.awt.Color(255, 255, 255));
        hargajual.setBorder(null);
        hargajual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargajualActionPerformed(evt);
            }
        });
        jPanel1.add(hargajual, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 335, 335, 19));

        hargabeli.setBackground(new java.awt.Color(255, 255, 255));
        hargabeli.setBorder(null);
        hargabeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargabeliActionPerformed(evt);
            }
        });
        jPanel1.add(hargabeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 278, 335, 19));

        stock.setBackground(new java.awt.Color(255, 255, 255));
        stock.setBorder(null);
        stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockActionPerformed(evt);
            }
        });
        jPanel1.add(stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 393, 335, 19));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 180, 430, 330));

        cari.setBackground(new java.awt.Color(255, 255, 255));
        cari.setBorder(null);
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cariKeyReleased(evt);
            }
        });
        jPanel1.add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 400, 30));

        home.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        home.setContentAreaFilled(false);
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        jPanel1.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, 70));

        EDIT.setContentAreaFilled(false);
        EDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDITActionPerformed(evt);
            }
        });
        jPanel1.add(EDIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 477, 90, 33));

        SIMPAN.setContentAreaFilled(false);
        SIMPAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIMPANActionPerformed(evt);
            }
        });
        jPanel1.add(SIMPAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 477, 80, 30));

        Hapus.setContentAreaFilled(false);
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });
        jPanel1.add(Hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 477, 85, 30));

        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 80, 70));

        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 10, 80, 70));

        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 80, 70));

        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 80, 70));

        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 80, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/BARANG.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hargajualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargajualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargajualActionPerformed

    private void SIMPANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIMPANActionPerformed
        // TODO add your handling code here:
         if(this.nama_barang.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "isi nama barang terlebih dahulu!");
            return;
        }else if(this.hargabeli.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "isi harga beli terlebih dahulu!");
            return;
        }else if(this.hargajual.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "isi harga jual supplier terlebih dahulu!");
            return;
        }else if(stock.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "isi stock terlebih dahulu!");
            return;
        }else{
        try {
            Connection conn = koneksi.getConnection();
            PreparedStatement stmt = conn.prepareStatement("insert into barang(id_barang, nama_barang, harga_beli, harga_jual, stock) values(?,?,?,?,?)");
            stmt.setString(1, id_barang.getText());
            stmt.setString(2, nama_barang.getText());
            stmt.setString(3, hargabeli.getText());
            stmt.setString(4, hargajual.getText());
            stmt.setString(5, stock.getText());
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            TampilData();
            auto_kdBR();
            nama_barang.setText(null);
            hargabeli.setText(null);
            hargajual.setText(null);
            stock.setText(null);
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        clear();
        }
       
                 
    }//GEN-LAST:event_SIMPANActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int baris = jTable1.getSelectedRow();
id_barang.setText(DftTblModel_barang.getValueAt(baris, 0).toString());
nama_barang.setText(DftTblModel_barang.getValueAt(baris, 1).toString());
hargabeli.setText(DftTblModel_barang.getValueAt(baris, 2).toString());
hargajual.setText(DftTblModel_barang.getValueAt(baris, 3).toString());
stock.setText(DftTblModel_barang.getValueAt(baris, 4).toString());
       
    }//GEN-LAST:event_jTable1MouseClicked

    private void EDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDITActionPerformed

// TODO add your handling code here:
String idBarang = this.id_barang.getText(),
                    namaBarang = this.nama_barang.getText(),
                    hargaBarang = this.hargabeli.getText(),
                    hargaBarang1 = this.hargajual.getText(),
                    stockBarang = this.stock.getText();
        try {
            String sql = String.format("UPDATE barang SET nama_barang = '%s', harga_beli = '%s',harga_jual = '%s', stock = '%s'  WHERE id_barang = '%s'", namaBarang, hargaBarang,hargaBarang1,
                    stockBarang, idBarang);
             Connection conn = koneksi.getConnection();
            Statement stat = conn.createStatement();
            stat.executeUpdate(sql);
            this.TampilData();
            JOptionPane.showMessageDialog(this, "data berhasil terupdate");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
    }//GEN-LAST:event_EDITActionPerformed
        
    }
    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        String id = jTable1.getValueAt(this.jTable1.getSelectedRow(),0).toString();
        // TODO add your handling code here:
        try {
            String sql = ("DELETE FROM barang WHERE id_barang = '"+id+"'");
        Connection conn = koneksi.getConnection();
         Statement stat = conn.createStatement();
         stat.executeUpdate(sql);
          this.TampilData();
          auto_kdBR();
            this.nama_barang.setText("");
            this.hargabeli.setText("");
            this.hargajual.setText("");
            this.stock.setText("");
             JOptionPane.showMessageDialog(this, "data berhasil di hapus ");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_HapusActionPerformed

    private void id_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_barangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_barangActionPerformed

    private void id_barangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id_barangKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_id_barangKeyPressed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        this.setVisible(false);
        new dashboard1().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_homeActionPerformed

    private void stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockActionPerformed

    private void hargabeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargabeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargabeliActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cariActionPerformed

    private void cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariKeyReleased
        // TODO add your handling code here:
        String key=cari.getText();
        System.out.println(key);
        
        if(key!=""){
            cariData(key);
        }else{
            TampilData();
        }
    }//GEN-LAST:event_cariKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        new supplier().setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        new transaksipenjualan().setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
        new laporan().setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.setVisible(false);
        new transaksipembelian().setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(barang1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(barang1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(barang1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(barang1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new barang1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EDIT;
    private javax.swing.JButton Hapus;
    private javax.swing.JButton SIMPAN;
    private javax.swing.JTextField cari;
    private javax.swing.JTextField hargabeli;
    private javax.swing.JTextField hargajual;
    private javax.swing.JButton home;
    private javax.swing.JTextField id_barang;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nama_barang;
    private javax.swing.JTextField stock;
    // End of variables declaration//GEN-END:variables
}
