/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package base;

import java.awt.Toolkit;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class register extends javax.swing.JFrame {

    private int waktumulai =0;
    /**
     * Creates new form register
     */
    public register() {
        initComponents();
        this.setTitle("Register");
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/tampilan/icon.png")));
        this.register.setOpaque(false);
        this.register.setContentAreaFilled(false);
        this.register.setBorderPainted(false);
        JamRealTime();
    }
     private void JamRealTime (){
    new Thread (){
        @Override
        public void run(){
            while(waktumulai == 0){
                Calendar kalender = new GregorianCalendar();
                int jam     = kalender.get(Calendar.HOUR);
                int menit   = kalender.get(Calendar.MINUTE);
                int detik   = kalender.get(Calendar.SECOND);
                int AMPM    = kalender.get(Calendar.AM_PM);
                String SiangMalam;
                if ( AMPM == 1){
                    SiangMalam = "PM";
                }else{
                    SiangMalam = "AM";
                }
                String JamRealTime = jam + ":" + menit + ":" + detik + "" + SiangMalam;
                labeljamreal.setText("Jam " + JamRealTime);
            }
        }
    }.start();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtUlangi = new javax.swing.JTextField();
        register = new javax.swing.JButton();
        back = new javax.swing.JButton();
        labeljamreal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsername.setBackground(new java.awt.Color(252, 253, 255));
        txtUsername.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 193, 303, 29));

        txtPassword.setBackground(new java.awt.Color(252, 253, 255));
        txtPassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 255, 303, 29));

        txtUlangi.setBackground(new java.awt.Color(252, 253, 255));
        txtUlangi.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtUlangi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUlangiActionPerformed(evt);
            }
        });
        getContentPane().add(txtUlangi, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 319, 303, 29));

        register.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        register.setContentAreaFilled(false);
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        getContentPane().add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 375, 300, 36));

        back.setContentAreaFilled(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 430, 40, 10));

        labeljamreal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labeljamreal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labeljamreal.setText("JAM");
        labeljamreal.setMaximumSize(new java.awt.Dimension(50, 29));
        labeljamreal.setMinimumSize(new java.awt.Dimension(50, 29));
        labeljamreal.setPreferredSize(new java.awt.Dimension(50, 29));
        getContentPane().add(labeljamreal, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 220, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/REGISTER.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUlangiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUlangiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUlangiActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        String username = txtUsername.getText();
        String sql = "SELECT id_login, username, password FROM login WHERE username = '"+ username+ "'";
        String password = txtPassword.getText();
        String Ulangi = txtUlangi.getText();
        System.out.println(password);
        System.out.println(Ulangi);
        String dataId = "";
        String dataUsername = "";
        String dataPassword = "";
        String dataSelected = "";
        int id;
        try {
            Connection conn = koneksi.getConnection();
            java.sql.Statement stmt = conn.createStatement();
            java.sql.ResultSet rs = stmt.executeQuery(sql);
            while(rs.next()){
                dataId = rs.getString("id_login");
                dataUsername = rs.getString("username");
                dataPassword = rs.getString("password");
            }
            System.out.println(dataUsername);
            System.out.println(dataPassword);
            if(dataUsername.equals(username)){
                JOptionPane.showMessageDialog(rootPane,"AKUN ANDA SUDAH ADA ");
                txtUsername.setText("");
                txtPassword.setText("");
                txtUlangi.setText("");
//            }else if(password != Ulangi){
//                System.out.println("data pasword "+password);
//                System.out.println("data ulangi "+Ulangi);
//                JOptionPane.showMessageDialog(rootPane,"PASSWORD HARUS SAMA");
//                txtUsername.setText("");
//                txtPassword.setText("");
//                txtUlangi.setText("");
            }else{
                String sql1 = "SELECT id_login FROM login ORDER BY id_login DESC LIMIT 1";
                rs = stmt.executeQuery(sql1);
                while(rs.next()){
                    dataSelected = rs.getString("id_login");
                    System.out.println("data yg dipilih "+dataSelected);
                }
                String clean = dataSelected.replaceAll("\\D+","");
                id = Integer.parseInt(clean)+1;
                if(id >=100 && id <1000){
                    dataSelected = "lg"+id;
                }else if(id<100 && id>=10){
                    dataSelected = "lg0"+id;
                }else if(id<10){
                    dataSelected = "lg00"+id;
                }
                System.out.println(dataSelected);
//                System.out.println("id adalah "+String.format("%03d", id));
                PreparedStatement stmt1 = conn.prepareStatement("insert into login(id_login ,username,password) values(?,?,?)");
                stmt1.setString(1, dataSelected);
                stmt1.setString(2, username);
                stmt1.setString(3, password);
                stmt1.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil disimpan", "Pesan", JOptionPane.INFORMATION_MESSAGE);
                JOptionPane.showMessageDialog(rootPane,"SELAMAT AKUN ANDA BERHASIL DI BUAT ");
                new login1().setVisible(true);
                dispose();
            }
        }catch (SQLException ex) {
            Logger.getLogger(login1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_registerActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
 new login1().setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labeljamreal;
    private javax.swing.JButton register;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUlangi;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
