/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package base;

/**
 *
 * @author HP
 */
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class supplier extends javax.swing.JFrame {
    DefaultTableModel tabModel;
    ResultSet RsSupplier=null;
    
    
    private DefaultTableModel DftTblModel_supplier;
private String SQL;
public void TampilData() {
     DftTblModel_supplier = new DefaultTableModel();
        DftTblModel_supplier.addColumn("ID Supplier");
        DftTblModel_supplier.addColumn("Nama Supplier");
        DftTblModel_supplier.addColumn("No Telp Supplier");
        DftTblModel_supplier.addColumn("Alamat Supplier");

       
         
        jTable1.setModel(DftTblModel_supplier);
       Connection conn = koneksi.getConnection();
        try {
            java.sql.Statement stmt = conn.createStatement();
            SQL = "select id_supplier, nama_supplier, no_telp_supplier, alamat_supplier from supplier";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()) {
                DftTblModel_supplier.addRow(new Object[]{
                    res.getString("id_supplier"),
                    res.getString("nama_supplier"),
                    res.getString("no_telp_supplier"),
                    res.getString("alamat_supplier"),
                });
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    private void cariData(String key){
         DftTblModel_supplier = new DefaultTableModel();
        DftTblModel_supplier.addColumn("ID Supplier");
        DftTblModel_supplier.addColumn("Nama Supplier");
        DftTblModel_supplier.addColumn("No Telp Supplier");
        DftTblModel_supplier.addColumn("Alamat Supplier");
         
        jTable1.setModel(DftTblModel_supplier);
       Connection conn = koneksi.getConnection();
        try {
            java.sql.Statement stmt = conn.createStatement();
            SQL = "select *  from supplier WHERE id_supplier LIKE '%"+key+"%'"
                    + " OR nama_supplier LIKE '%"+key+"%' or no_telp_supplier LIKE '%"+key+"%' "
                    + "or alamat_supplier LIKE '%"+key+"%'";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()) {
                DftTblModel_supplier.addRow(new Object[]{
                    res.getString("id_supplier"),
                    res.getString("nama_supplier"),
                    res.getString("no_telp_supplier"),
                    res.getString("alamat_supplier")
                });
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }   
    }
    
    private void auto_kdSP() {
        try{
        String sql = "SELECT MAX(RIGHT(id_supplier,3)) FROM supplier";
        java.sql.Connection con = (Connection) koneksi.getConnection();
        java.sql.Statement st = con.createStatement();
        java.sql.ResultSet rst = st.executeQuery(sql);
        if(rst.next()) {
            String auto_kdPM, tambah;
            int kdb;
            auto_kdPM = Integer.toString(rst.getInt(1)+1);
            kdb = auto_kdPM.length();
            tambah = "";
            for (int i = 1; i <= 3 - kdb; i++ ){
                tambah = tambah + "0";
            }
            id_supplier.setText("SP"+tambah+auto_kdPM);
            }
        }
        catch (Exception e) {
            id_supplier.setText("Sp001");
        }
    }
    
    public void clear(){
        auto_kdSP();
        nama_supplier.setText("");
        no_telp_supplier.setText("");
        alamat_supplier.setText("");
    }



    /**
     * Creates new form supplier
     */
    public supplier() {
        initComponents();
        TampilData();
        auto_kdSP();
        clear();
        this.setTitle("Supplier");
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/tampilan/icon.png")));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        nama_supplier = new javax.swing.JTextField();
        id_supplier = new javax.swing.JTextField();
        no_telp_supplier = new javax.swing.JTextField();
        alamat_supplier = new javax.swing.JTextField();
        cari = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        SIMPAN = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 420, 330));

        nama_supplier.setBackground(new java.awt.Color(255, 255, 255));
        nama_supplier.setBorder(null);
        getContentPane().add(nama_supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 221, 335, 19));

        id_supplier.setBackground(new java.awt.Color(255, 255, 255));
        id_supplier.setBorder(null);
        getContentPane().add(id_supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 165, 335, 19));

        no_telp_supplier.setBackground(new java.awt.Color(255, 255, 255));
        no_telp_supplier.setBorder(null);
        getContentPane().add(no_telp_supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 278, 335, 19));

        alamat_supplier.setBackground(new java.awt.Color(255, 255, 255));
        alamat_supplier.setBorder(null);
        getContentPane().add(alamat_supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 335, 335, 19));

        cari.setBackground(new java.awt.Color(255, 255, 255));
        cari.setBorder(null);
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cariKeyReleased(evt);
            }
        });
        getContentPane().add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 99, 400, 30));
        cari.getAccessibleContext().setAccessibleName("");

        back.setContentAreaFilled(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, 70));

        SIMPAN.setContentAreaFilled(false);
        SIMPAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIMPANActionPerformed(evt);
            }
        });
        getContentPane().add(SIMPAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 485, 80, 30));

        edit.setContentAreaFilled(false);
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 485, 84, 30));

        hapus.setContentAreaFilled(false);
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 485, 82, 30));

        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 80, 80));

        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 70, 80));

        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 60, 70));

        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, 70, 80));

        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 60, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/SUPPLIER1.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLabel2KeyReleased(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
  this.setVisible(false);
        new dashboard1().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void SIMPANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIMPANActionPerformed
        // TODO add your handling code here:
        if(this.nama_supplier.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "isi nama supplier terlebih dahulu!");
            return;
        }else if(this.no_telp_supplier.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "isi no telp terlebih dahulu!");
            return;
        }else if(this.alamat_supplier.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "isi alamat supplier terlebih dahulu!");
            return;
        }else if(no_telp_supplier.getText().length() < 8 || no_telp_supplier.getText().length() >= 13){
             JOptionPane.showMessageDialog(null, "Masukuan Nomer Telepon Dengan Benar", "ERROR", JOptionPane.ERROR_MESSAGE);
             return;
         }else{
            try{

            try {
                String sql = "INSERT INTO tbl_suplier VALUES ('"+id_supplier.getText()+"', '" + nama_supplier.getText() + "', '" + no_telp_supplier.getText()
                + "', '" + alamat_supplier.getText() + "')";
                System.out.println(sql);
                java.sql.Connection conn = (Connection) koneksi.getConnection();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Data Berhasil Diedit");
                clear();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Perubahan data gagal" + e.getMessage());
            }
            TampilData();
            clear();
         
        }catch(Exception e){
         JOptionPane.showMessageDialog(null, "Masukuan Nomer Telepon Dengan Benar", "ERROR", JOptionPane.ERROR_MESSAGE);
    }
         try {
            Connection conn = koneksi.getConnection();
            PreparedStatement stmt = conn.prepareStatement("insert into supplier(id_supplier, nama_supplier, no_telp_supplier, alamat_supplier) values(?,?,?,?)");
            stmt.setString(1, id_supplier.getText());
            stmt.setString(2, nama_supplier.getText());
            stmt.setString(3, no_telp_supplier.getText());
            stmt.setString(4, alamat_supplier.getText());
//            stmt.setString(5, namabarang.getText());
//            stmt.setString(6, harga.getText());
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            TampilData();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
       TampilData();
       clear();
        }

    }//GEN-LAST:event_SIMPANActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        String idsupplier = this.id_supplier.getText(),
                    namasupplier = this.nama_supplier.getText(),
                    no_telp = this.no_telp_supplier.getText(),
                    alamat = this.alamat_supplier.getText();     
        
         if(no_telp_supplier.getText().length() < 8 || no_telp_supplier.getText().length() >= 13){
             JOptionPane.showMessageDialog(null, "Masukuan Nomer Telepon Dengan Benar", "ERROR", JOptionPane.ERROR_MESSAGE);
             return;
         }
         
        try {
            String sql = String.format("UPDATE supplier SET nama_supplier = '%s', no_telp_supplier = '%s',  alamat_supplier = '%s' WHERE id_supplier = '%s'", 
                    namasupplier, no_telp, alamat,idsupplier);
             Connection conn = koneksi.getConnection();
            Statement stat = conn.createStatement();
            stat.executeUpdate(sql);
            this.TampilData();
            JOptionPane.showMessageDialog(this, "data berhasil terupdate");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
    }                      
        clear();
    }//GEN-LAST:event_editActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
         String id = jTable1.getValueAt(this.jTable1.getSelectedRow(),0).toString();
           try {
            String sql = ("DELETE FROM supplier WHERE id_supplier = '"+id+"'");
        Connection conn = koneksi.getConnection();
         Statement stat = conn.createStatement();
         stat.executeUpdate(sql);
          this.TampilData();
            this.id_supplier.setText("");
            this.nama_supplier.setText("");
            this.no_telp_supplier.setText("");
            this.alamat_supplier.setText("");
             JOptionPane.showMessageDialog(this, "data berhasil di hapus ");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
           clear();
    }//GEN-LAST:event_hapusActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         int baris = jTable1.getSelectedRow();
id_supplier.setText(DftTblModel_supplier.getValueAt(baris, 0).toString());
nama_supplier.setText(DftTblModel_supplier.getValueAt(baris, 1).toString());
no_telp_supplier.setText(DftTblModel_supplier.getValueAt(baris, 2).toString());
alamat_supplier.setText(DftTblModel_supplier.getValueAt(baris, 3).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cariActionPerformed

    private void jLabel2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2KeyReleased

    private void cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariKeyReleased
        // TODO add your handling code here:
        String key=cari.getText();
        System.out.println(key);
        
        if(key!=""){
            cariData(key);
        }else{
            TampilData();
        }
    }//GEN-LAST:event_cariKeyReleased

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.setVisible(false);
        new barang1().setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        new transaksipembelian().setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
        new transaksipenjualan().setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setVisible(false);
        new laporan().setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.setVisible(false);
        new login1().setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new supplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SIMPAN;
    private javax.swing.JTextField alamat_supplier;
    private javax.swing.JButton back;
    private javax.swing.JTextField cari;
    private javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField id_supplier;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nama_supplier;
    private javax.swing.JTextField no_telp_supplier;
    // End of variables declaration//GEN-END:variables
}
